/// <reference types="cypress" />

context('Build a robot', () => {
  beforeEach(() => {
    cy.visit('http://localhost:4200/')
  })

  it('Make enough foos', () => {
    cy
    // Make 20 foos
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_mineFoo]`).click()
    // Make 10 bars
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    .get(`[data-cy=robot_0]`).click()
    .get(`[data-cy=robot_0_action_mineBar]`).click()
    // Make up to 10 foobars
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buildFoobar]`).click()
    // Sell foobars
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_sell]`).click()
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_sell]`).click()
    // Buy a 3rd robot
    .get(`[data-cy=robot_1]`).click()
    .get(`[data-cy=robot_1_action_buy]`).click()
  })
})